# Generated by Django 4.1.3 on 2022-12-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
